// Generated by CoffeeScript 1.4.0
var echo;

echo = (function() {

  function echo() {}

  echo.prototype.exe = function(args, response) {
    args.shift();
    return response.send({
      stdout: args
    });
  };

  return echo;

})();

module.exports = echo;
