// Generated by CoffeeScript 1.4.0
var _;

_ = require('underscore');

_.str = require('underscore.string');

module.exports.tokenize = function(input) {
  var matches, pattern, trimmedMatches;
  pattern = new RegExp('\w+|"[^"]+"', 'gi');
  matches = input.match(/\w+|"(?:\\"|[^"])+"/g);
  trimmedMatches = _(matches).map(function(token) {
    return _.str.trim(token, '"');
  });
  return trimmedMatches;
};
