// Generated by CoffeeScript 1.4.0
var Config, help, querystring, _,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

_ = require('underscore');

Config = require('./config/config');

querystring = require('querystring');

help = (function() {

  function help(user) {
    this.user = user;
    this.exe = __bind(this.exe, this);

  }

  help.prototype.helpText = "<p>werminal is a command line interface wired for the web, and designed with simplicity in mind.</p>\n<p>Type commands in the input box, and press ENTER to execute them.</p>\n<p>werminal is built around <strong>services</strong> that perform various functions.  Some, like this <strong>help</strong> service, just output helpful text.  Others perform transformations or interface with third party platforms.</p>\n<p>Many services, particularly those that connect to third parties, require you to login by clicking the link at the top of this page.</p>\n<p>Type <strong>services</strong> to see a list of available services.</p>";

  help.prototype.exe = function(args, response) {
    return response.send({
      stdout: this.helpText,
      template: Config.expandURL('/blank.html')
    });
  };

  return help;

})();

module.exports = help;
