// Generated by CoffeeScript 1.4.0
var Config, querystring, services, tokenTree, _;

_ = require('underscore');

Config = require('./config/config');

querystring = require('querystring');

tokenTree = require('./tokenTree');

services = (function() {

  function services(user) {
    this.user = user;
  }

  services.prototype.exe = function(args, response) {
    var serviceNames, servicesHTML;
    serviceNames = _(tokenTree._tokens).map(function(value, key) {
      return '<li><span class="service-name">' + key + '</span><span class="description">' + value._desc + '</span></li>';
    });
    servicesHTML = '<ul class="services">' + serviceNames.join('') + '</ul>';
    return response.send({
      stdout: servicesHTML,
      template: Config.expandURL('/blank.html')
    });
  };

  return services;

})();

module.exports = services;
